services:
  postgres:
    container_name: postgres-dbs2
    image: postgres:18-alpine3.24
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - ./mnt/:/var/lib/postgresql/18/docker
      - ./src/:/src