-- Rebuild the task tables in the current schema/search_path.
-- Source IDs remain source IDs unless a table explicitly has a local surrogate ID.

-- Lookup tables
CREATE TABLE IF NOT EXISTS enum_parse_statuses (
    status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS enum_match_statuses (
    status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS enum_run_statuses (
    status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS enum_file_statuses (
    status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS enum_curated_statuses (
    status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    status_code TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS enum_datasets (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dataset TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_document_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_ocr_sources (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_entity_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_person_categories (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_kg_entity_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_relationship_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_event_tracks (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, track TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_event_types (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_event_confidences (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_participant_roles (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_curated_tiers (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tier TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_curated_subjects (id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subject TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS enum_models (model_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, model_name TEXT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT PRIMARY KEY,                         -- source documents.id
    file_key TEXT NOT NULL UNIQUE,
    dataset SMALLINT NOT NULL REFERENCES enum_datasets(id) ON DELETE RESTRICT,
    full_text TEXT NOT NULL,
    document_type SMALLINT REFERENCES enum_document_types(id) ON DELETE RESTRICT,
    date_raw TEXT,
    date_parsed DATE,
    date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    is_photo BOOLEAN NOT NULL,
    has_handwriting BOOLEAN,
    has_stamps BOOLEAN,
    ocr_source SMALLINT REFERENCES enum_ocr_sources(id) ON DELETE RESTRICT,
    additional_notes TEXT,
    page_number TEXT,                               -- mixed source notation; preserve as text
    document_number TEXT,
    char_count INTEGER NOT NULL CHECK (char_count >= 0),
    created_at_raw TEXT NOT NULL,
    created_at_parsed TIMESTAMP WITHOUT TIME ZONE,
    created_at_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    email_fields_raw TEXT,
    email_fields_parsed JSONB,
    email_fields_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT
);

-- The chunks layer was already profiled; retain its source columns and full source IDs.
CREATE TABLE IF NOT EXISTS chunks (
    id BIGINT PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE RESTRICT,
    chunk_index INTEGER,
    token_count INTEGER,
    char_start INTEGER,
    char_end INTEGER,
    content TEXT,
    UNIQUE (document_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS entities (
    id BIGINT PRIMARY KEY,
    document_id_raw BIGINT NOT NULL,                -- source reference; distinct from resolved FK; includes unresolved values
    document_id BIGINT REFERENCES documents(id) ON DELETE RESTRICT,
    document_match_status SMALLINT NOT NULL REFERENCES enum_match_statuses(status_id) ON DELETE RESTRICT,
    entity_type_id SMALLINT NOT NULL REFERENCES enum_entity_types(id) ON DELETE RESTRICT,
    value_raw TEXT NOT NULL,                        -- original extracted mention, not verified identity
    normalized_value_raw TEXT,                     -- upstream column; all NULL in this revision
    normalized_value_parsed TEXT,                   -- reserved for an explicitly versioned rule; currently NULL
    normalization_rule TEXT                         -- rule/version; currently NULL because no normalization is applied
);

CREATE TABLE IF NOT EXISTS persons (
    id BIGINT PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    slug TEXT NOT NULL,
    category_id SMALLINT NOT NULL REFERENCES enum_person_categories(id) ON DELETE RESTRICT,
    aliases_raw TEXT NOT NULL,
    aliases_parsed JSONB,
    aliases_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    search_terms_raw TEXT NOT NULL,
    search_terms_parsed JSONB,
    search_terms_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    sources_raw TEXT NOT NULL,
    sources_parsed JSONB,
    sources_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    notes TEXT                                      -- retained although NULL throughout this revision
);

CREATE TABLE IF NOT EXISTS kg_entities (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    entity_type_id SMALLINT NOT NULL REFERENCES enum_kg_entity_types(id) ON DELETE RESTRICT,
    description TEXT,                               -- retained although NULL throughout this revision
    metadata_raw TEXT NOT NULL,
    metadata_parsed JSONB,
    metadata_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS kg_relationships (
    id BIGINT PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES kg_entities(id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL REFERENCES kg_entities(id) ON DELETE RESTRICT,
    relationship_type_id SMALLINT NOT NULL REFERENCES enum_relationship_types(id) ON DELETE RESTRICT,
    weight DOUBLE PRECISION NOT NULL,               -- source Float64; not a probability
    evidence TEXT,                                   -- retained although NULL throughout this revision
    metadata_raw TEXT NOT NULL,
    metadata_parsed JSONB,
    metadata_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS derived_events (
    id BIGINT PRIMARY KEY,
    event_date_raw TEXT,
    event_date_parsed DATE,
    event_date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    event_end_date_raw TEXT,
    event_end_date_parsed DATE,
    event_end_date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    event_type_id SMALLINT NOT NULL REFERENCES enum_event_types(id) ON DELETE RESTRICT,
    track_id SMALLINT NOT NULL REFERENCES enum_event_tracks(id) ON DELETE RESTRICT,
    headline TEXT NOT NULL,
    location TEXT,
    amount NUMERIC,                                 -- Decimal(str(source Float64)); no cents rounding
    currency TEXT NOT NULL,
    payer TEXT,                                     -- retained although NULL throughout this revision
    payee TEXT,
    route_from TEXT,
    route_to TEXT,
    aircraft TEXT,                                  -- retained although NULL throughout this revision
    time_of_day_raw TEXT,
    confidence_id SMALLINT NOT NULL REFERENCES enum_event_confidences(id) ON DELETE RESTRICT,
    narrative TEXT
);

CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES derived_events(id) ON DELETE RESTRICT,
    person_name TEXT NOT NULL,                       -- not automatically linked to persons.id
    role_id SMALLINT NOT NULL REFERENCES enum_participant_roles(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS event_sources (
    id BIGINT PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES derived_events(id) ON DELETE RESTRICT,
    file_key TEXT NOT NULL,                          -- raw upstream evidence key
    document_id BIGINT REFERENCES documents(id) ON DELETE RESTRICT,
    document_match_status SMALLINT NOT NULL REFERENCES enum_match_statuses(status_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS financial_transactions (
    id BIGINT PRIMARY KEY,
    file_key TEXT NOT NULL,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE RESTRICT,
    dataset_id SMALLINT NOT NULL REFERENCES enum_datasets(id) ON DELETE RESTRICT,
    transaction_date_raw TEXT,
    transaction_date_parsed DATE,
    transaction_date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    amount NUMERIC,                                  -- source Float64; preserve displayed scale/sign
    currency TEXT NOT NULL,
    merchant_name TEXT,
    merchant_raw TEXT,                               -- original extracted merchant string
    merchant_category TEXT,
    location TEXT,
    cardholder TEXT,
    description TEXT,
    card_type TEXT,
    account_digits TEXT,                             -- identifier; preserve leading zeroes
    statement_date_raw TEXT,
    statement_date_parsed DATE,
    statement_date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    flight_from TEXT,
    flight_to TEXT,
    flight_carrier TEXT,
    flight_departure_raw TEXT,
    flight_departure_parsed DATE,
    flight_departure_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    flight_ticket TEXT,
    flight_passenger TEXT,
    source_page INTEGER,                             -- retained although NULL throughout this revision
    extraction_model_raw TEXT NOT NULL,
    extraction_model_id SMALLINT REFERENCES enum_models(model_id) ON DELETE RESTRICT,
    extraction_model_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    extraction_confidence DOUBLE PRECISION           -- retained although NULL throughout this revision
);

CREATE TABLE IF NOT EXISTS curated_docs (
    id BIGINT PRIMARY KEY,
    file_key TEXT NOT NULL,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE RESTRICT,
    subject_id SMALLINT NOT NULL REFERENCES enum_curated_subjects(id) ON DELETE RESTRICT,
    curated_status SMALLINT NOT NULL REFERENCES enum_curated_statuses(status_id) ON DELETE RESTRICT,
    tier_id SMALLINT NOT NULL REFERENCES enum_curated_tiers(id) ON DELETE RESTRICT,
    category TEXT NOT NULL,
    doc_date_raw TEXT,
    doc_date_parsed DATE,
    doc_date_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    doc_from TEXT,
    doc_to TEXT,
    headline TEXT,
    key_quote TEXT,
    detail TEXT,
    thread_value TEXT,
    also_appears_as_raw TEXT,
    also_appears_as_parsed JSONB,
    also_appears_as_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT
);

-- Upstream runs are distinct from this project's own import-run log.
CREATE TABLE IF NOT EXISTS provenance_runs (
    run_id TEXT PRIMARY KEY,                         -- 112 UUID-shaped and 11 non-UUID source IDs
    started_at_raw TEXT NOT NULL,
    started_at_parsed TIMESTAMPTZ,
    started_at_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    completed_at_raw TEXT NOT NULL,
    completed_at_parsed TIMESTAMPTZ,
    completed_at_local_parsed TIMESTAMP WITHOUT TIME ZONE,
    completed_at_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    run_status SMALLINT NOT NULL REFERENCES enum_run_statuses(status_id) ON DELETE RESTRICT,
    input_dir TEXT NOT NULL,
    output_name TEXT NOT NULL,
    model_raw TEXT NOT NULL,
    model_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    dpi INTEGER NOT NULL,
    workers INTEGER NOT NULL,
    rpm INTEGER NOT NULL,
    git_commit TEXT,
    hostname TEXT,
    total_files INTEGER NOT NULL,
    success_count INTEGER NOT NULL,
    fail_count INTEGER NOT NULL,
    input_tokens BIGINT NOT NULL,
    output_tokens BIGINT NOT NULL,
    cost_usd NUMERIC NOT NULL,
    last_heartbeat_raw TEXT,
    last_heartbeat_parsed TIMESTAMPTZ,
    last_heartbeat_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS provenance_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    source_row BIGINT NOT NULL CHECK (source_row >= 0),
    file_key TEXT NOT NULL,
    output_name TEXT NOT NULL,
    pdf_path TEXT NOT NULL,
    pdf_sha256_raw TEXT,
    pdf_sha256_parsed BYTEA CHECK (pdf_sha256_parsed IS NULL OR octet_length(pdf_sha256_parsed) = 32),
    pdf_sha256_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    pdf_size_bytes BIGINT,
    file_status SMALLINT NOT NULL REFERENCES enum_file_statuses(status_id) ON DELETE RESTRICT,
    output_path TEXT,
    output_sha256_raw TEXT,
    output_sha256_parsed BYTEA CHECK (output_sha256_parsed IS NULL OR octet_length(output_sha256_parsed) = 32),
    output_sha256_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    first_seen_at_raw TEXT NOT NULL,
    first_seen_at_parsed TIMESTAMPTZ,
    first_seen_at_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    processed_at_raw TEXT NOT NULL,
    processed_at_parsed TIMESTAMPTZ,
    processed_at_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    run_id TEXT REFERENCES provenance_runs(run_id) ON DELETE RESTRICT,
    document_id BIGINT REFERENCES documents(id) ON DELETE RESTRICT,
    document_match_status SMALLINT NOT NULL REFERENCES enum_match_statuses(status_id) ON DELETE RESTRICT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    api_latency_ms BIGINT,
    attempts INTEGER NOT NULL,
    error_message TEXT,
    model_used_raw TEXT NOT NULL,
    model_used_status SMALLINT NOT NULL REFERENCES enum_parse_statuses(status_id) ON DELETE RESTRICT,
    validation_score SMALLINT,
    UNIQUE (source_file, source_row)
);

-- Preserve each source model token and its order while normalizing model names.
CREATE TABLE IF NOT EXISTS provenance_run_models (
    run_id TEXT NOT NULL REFERENCES provenance_runs(run_id) ON DELETE CASCADE,
    model_id SMALLINT NOT NULL REFERENCES enum_models(model_id) ON DELETE RESTRICT,
    PRIMARY KEY (run_id, model_id)
);
CREATE TABLE IF NOT EXISTS provenance_file_models (
    file_id BIGINT NOT NULL REFERENCES provenance_files(id) ON DELETE CASCADE,
    model_id SMALLINT NOT NULL REFERENCES enum_models(model_id) ON DELETE RESTRICT,
    PRIMARY KEY (file_id, model_id)
);
